# runtime: nodejs
# env: flex
# runtime: nodejs10

# entrypoint: node ./Backend/server/server.js

# env_variables:
# CLOUD_INSTANCE: behavior-app-278623:us-central1:behavior-app-database

# instance_class: F2
# resources:
# memory_gb: 0.25
