export const FETCH_STUDENTS = "FETCH_STUDENTS";
export const NEW_STUDENT = "NEW_STUDENT";
export const FETCH_PREFERREDBEHAVIOR = "FETCH_PREFERREDBEHAVIOR";
export const FETCH_NONPREFERREDBEHAVIOR = "FETCH_NONPREFERREDBEHAVIOR";
export const NEW_PREFERREDBEHAVIOR = "NEW_PREFERREDBEHAVIOR";
export const NEW_NONPREFERREDBEHAVIOR = "NEW_NONPREFERREDBEHAVIOR";
